name: Build and Upload Go Executable

on:
  release:
    types: [created]  # 当创建新的 Release 时触发

permissions:
    contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23.2'

      - name: Build Go Executable
        run: |
          go build -o mirrors .

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          tag: ${{ github.event.release.tag_name }}  # 使用创建的 Release 标签
          files: ./mirrors  # 上传的文件路径
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
